// Renders dist/ical/status.html (see main() in build-ical.js): one row per
// district menu with how far ahead it's posted and when the district last
// edited it. The README's menu badges link here. Plain static HTML, no
// scripts - it's regenerated by every daily build.

const TZ = "America/Chicago";

const escapeHtml = (s) =>
  String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

// "2026-11-20" -> "Fri, Nov 20, 2026" (a calendar date, so no time zone
// shifting - parsed and printed as UTC).
function formatDate(ymd) {
  const [y, m, d] = ymd.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    weekday: "short", month: "short", day: "numeric", year: "numeric", timeZone: "UTC",
  });
}

const formatTimestamp = (date) =>
  date.toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", timeZoneName: "short", timeZone: TZ,
  });

// menus: [{ name, lastDate: "YYYY-MM-DD" | null, updatedAt: unix seconds | null }]
export function renderStatusPage(menus, generatedAt) {
  const rows = menus
    .map(({ name, lastDate, updatedAt }) => `      <tr>
        <td>${escapeHtml(name)}</td>
        <td>${lastDate ? `<time datetime="${lastDate}">${formatDate(lastDate)}</time>` : "&mdash;"}</td>
        <td>${updatedAt ? `<time datetime="${new Date(updatedAt * 1000).toISOString()}">${formatTimestamp(new Date(updatedAt * 1000))}</time>` : "&mdash;"}</td>
      </tr>`)
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Menu Status</title>
  <style>
    :root { color-scheme: light dark; --bg: #fff; --fg: #1a1a1a; --muted: #666; --line: #ddd; --stripe: #f6f6f6; }
    @media (prefers-color-scheme: dark) {
      :root { --bg: #121212; --fg: #e8e8e8; --muted: #999; --line: #333; --stripe: #1b1b1b; }
    }
    body { margin: 0; padding: 24px 16px; background: var(--bg); color: var(--fg); font: 15px/1.45 system-ui, -apple-system, sans-serif; }
    main { max-width: 760px; margin: 0 auto; }
    h1 { font-size: 1.4rem; margin: 0 0 4px; }
    p { color: var(--muted); margin: 0 0 16px; }
    a { color: inherit; }
    .scroll { overflow-x: auto; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); white-space: nowrap; }
    td:first-child { white-space: normal; }
    th { font-weight: 600; }
    tbody tr:nth-child(odd) { background: var(--stripe); }
  </style>
</head>
<body>
  <main>
    <h1>Lindbergh School Menus &mdash; Status</h1>
    <p>How far ahead the district has posted each menu, and when it last edited it.
      Unofficial &mdash; <a href="https://tools.tuley.name/fix-lindbergh-school-menus/">menu viewer</a>
      &middot; <a href="https://github.com/jbtule/fix-lindbergh-school-menus">source</a>.</p>
    <div class="scroll">
    <table>
      <thead>
        <tr><th>Menu</th><th>Menus through</th><th>Last updated by district</th></tr>
      </thead>
      <tbody>
${rows}
      </tbody>
    </table>
    </div>
    <p style="margin-top:16px">Checked ${escapeHtml(formatTimestamp(generatedAt))}.</p>
  </main>
</body>
</html>
`;
}
